<?php

namespace BaseLine\Bundle\MiniBlogBundle\Repository;

/**
 * MinipostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinipostRepository extends \Doctrine\ORM\EntityRepository
{
}
